// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wahongwkmaaecbltyezo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhaG9uZ3drbWFhZWNibHR5ZXpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTg0NzMsImV4cCI6MjA2MTQzNDQ3M30.i1MkjMeQYLYkdIeRXTZghYCCnVpG9GNOjqUmyi4Ao7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);